In [24]:
import cv2
import numpy as np

img = cv2.imread('image.png')


In [61]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
px = img[100,100]
print(px)

# accessing only blue pixel
blue = img[100,100,0]
print(blue)


[255 255 255]
255


In [36]:
img[0:100,0:100] = [255,0,0]

In [42]:
for x in range (100):
    for y in range (100):
      img.itemset((50+x,50+y,1),20) # 지정된 다른 위치에 박스 생성, 20은 색상

In [45]:
print (img.shape) # 이미지 크기

(225, 225, 3)


In [46]:
print (img.size) # 이미지 용량

151875


In [47]:
print (img.dtype)

uint8


In [59]:
ball = img[20:50, 60:90]
img[70:100, 120:150] = ball
#  이미지의 한 부분을 떼서 다른 부분에 붙임

In [51]:
b,g,r = cv2.split(img)
img = cv2.merge((b,g,r))

In [53]:
print(img)

[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [54]:
b = img[:,:,0]

In [56]:
img[:,:,2] = 0